# For creating the package, I followed these tutorials:
# 	https://packaging.python.org/en/latest/tutorials/packaging-projects/
# 	https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

[project]
authors = [
  {name = "ppbrs", email = "prishchepenko.boris@gmail.com"},
]
dependencies = [
  "colorama >= 0.4",
  "psutil >= 5.9",
  "pyright >= 1.1",
  "ruff >= 0.15",
  "types-psutil >= 5.9",
  "types-colorama >= 0.4",
]
description = "Collection of tests and a CLI tool for my Obsidian vaults. Task tracker."
dynamic = [
  "version",
]
name = "dope"
readme = "README.md"
requires-python = ">=3.10"

# For a complete list of classifiers, see https://pypi.org/classifiers/.
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

# After installing the project, a `d` command will be available.
# Executing it will do the equivalent of `from dope import dope_cli; dope_cli()`.
[project.scripts]
d = "dope:dope_cli"

# [build-system] declares which build backend to use - a library that takes a source tree
# and builds a source distribution (*.tar.gz) or wheel (*.whl) from it.
# Examples:
# 	hatchling (https://packaging.python.org/en/latest/key_projects/#setuptools)
# 		https://pypi.org/project/hatchling/
# 	setuptools (https://packaging.python.org/en/latest/key_projects/#setuptools)
# 		https://pypi.org/project/setuptools/
# Also [build-system] allows declaring which dependencies are needed to build the project,
# see `requires`.
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1.18.0"]

[tool.hatch.version]
path = "dope/__about__.py"

[project.urls]
"Bug Tracker" = "https://github.com/ppbrs/dope/issues"
"Homepage" = "https://github.com/ppbrs/dope"

# ==================================================================================================
# pytest configuration
# ==================================================================================================
[tool.pytest.ini_options]
# Having pytest look for all files instead of "test_*.py" only:
python_files = "*.py"

# Logging level for failed tests:
log_date_format = "%H:%M:%S"
log_format = "%(asctime)s.%(msecs)03d %(levelname)s %(funcName)s: %(message)s"
log_level = "DEBUG"

# Logging level for real-time output:
log_cli = "True"
log_cli_level = "INFO"

markers = [
  """vault_test(boolean): mark a test to run on vaults, as opposed to on dope internals""",
]

# ==================================================================================================
# pyright
# ==================================================================================================
[tool.pyright]

exclude = []
include = ["dope"]

pythonPlatform = "Linux"
pythonVersion = "3.12"

# ==================================================================================================
# mypy
# ==================================================================================================
[tool.mypy]

strict = true

# ==================================================================================================
# ruff
# ==================================================================================================
[tool.ruff]

line-length = 100

# --------------------------------------------------------------------------------------------------
[tool.ruff.format]
# https://docs.astral.sh/ruff/formatter/

# Use double quotes for strings.
quote-style = "double"
# Indent with spaces, rather than tabs.
indent-style = "space"

docstring-code-format = true
docstring-code-line-length = 80

# --------------------------------------------------------------------------------------------------
[tool.ruff.lint]

# (https://docs.astral.sh/ruff/rules/)
select = [
  # "E", "W",  # Pycodestyle Errors and Warnings
  # "F",  # Pyflakes (Common errors like unused imports)
  "I",  # isort (Import sorting)
  # "UP",  # Pyupgrade (Modernize Python syntax)
  # "B",  # Flake8-bugbear (Subtle bugs and design issues)
  # "S",  # Bandit (Security checks)
  # "ANN",  # Flake8-annotations (Type hints enforcement)
  # "N",  # Pep8-naming (Naming conventions)
  # "D",  # Pydocstyle (Docstring formatting)
  # "RUF",  # Ruff-specific rules
]

[tool.ruff.lint.isort]

combine-as-imports = true  # Combines 'from x import y as z' onto one line
force-sort-within-sections = false  # Sorts alphabetically ignoring 'from' vs 'import'

# --------------------------------------------------------------------------------------------------
