#!/bin/bash

# This is a temporary script for creating `j`, a soft link to `jcli.py`.
# In the future, joplin-cli is going to be a python package.
#

JCLI_PATH=$PWD
rm ~/.local/bin/j
ln -s $JCLI_PATH/jcli.py ~/.local/bin/j
